export const CREATE_SCHEDULE_REQUEST = 'CREATE_SCHEDULE_REQUEST'
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS'
export const CREATE_SCHEDULE_FAILURE = 'CREATE_SCHEDULE_FAILURE'


export const FETCH_SCHEDULE_REQUEST = 'FETCH_SCHEDULE_REQUEST'
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS'
export const FETCH_SCHEDULE_FAILURE = 'FETCH_SCHEDULE_FAILURE'